### get user profile
GET http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNOVzEzIiwiaWF0IjoxNjczNDM0NzMwLCJleHAiOjE3MDQ5NzA3MzB9.DNO0kV3GcwMui02LOmUt14VPlCBIIqyymvJWAxqdCog


### get user profile
PATCH http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNOVzEzIiwiaWF0IjoxNjczNDM0NzMwLCJleHAiOjE3MDQ5NzA3MzB9.DNO0kV3GcwMui02LOmUt14VPlCBIIqyymvJWAxqdCog

{
  "first_name": "Saeed",
  "last_name": "Norouzi",
  "phone": "09364139756",
  "email": "saeed_nowrouzi98@hotmail.com",
  "password": "12345678900"
}

### get user team invitations
GET http://localhost:3000/user/invitations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZWVkLm5vcm91emkiLCJpYXQiOjE2NzM4OTE1NjYsImV4cCI6MTcwNTQyNzU2Nn0.rdOAeoYphKmoH091yXhTP8CjYiawwWY1bQgc2ExBEaE

### get user team invitations by status
GET http://localhost:3000/user/invitations/pending
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZWVkLm5vcm91emkiLCJpYXQiOjE2NzM4OTE1NjYsImV4cCI6MTcwNTQyNzU2Nn0.rdOAeoYphKmoH091yXhTP8CjYiawwWY1bQgc2ExBEaE

### update user invitation status
GET http://localhost:3000/user/invitations/update/63c550745928290808518991/accepted
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZWVkLm5vcm91emkiLCJpYXQiOjE2NzM4OTE1NjYsImV4cCI6MTcwNTQyNzU2Nn0.rdOAeoYphKmoH091yXhTP8CjYiawwWY1bQgc2ExBEaE